import { Attraction, Accommodation, Restaurant, TourismEvent, GalleryItem, BlogPost, FAQ, Establishment } from "./types";


export const ATTRACTIONS: Attraction[] = [
  {
    id: "tinuyan-falls",
    name: "Tinuy-an Falls",
    description: "The 'Niagara of the Philippines', a majestic 95-meter wide, three-tiered waterfall cascading amidst a deep emerald rainforest.",
    longDescription: "Known as the Crown Jewel of Bislig City, Tinuy-an Falls is a majestic multi-tiered waterfall that stretches 95 meters wide and plunges 55 meters high. Its name comes from the word 'tinuyo-an,' meaning an intentional act. The misty spray creates gorgeous natural rainbows on sunny mornings, typically between 9:00 AM and 11:00 AM. Visitors can take a bamboo raft (balsa) ride to get right under the cascading waters for a natural hydro-massage, or climb the paved stairs to the second and third tiers for breathtaking vantage points.",
    category: "Waterfalls",
    image: "/assets/images/Tinuy.an Featured 1.webp",
    distance: "18 km",
    travelTime: "35 mins",
    difficulty: "Easy",
    bestTime: "08:00 AM - 11:00 AM",
    entranceFee: "₱50.00 (Standard) / Children under 12 Free",
    openingHours: "06:00 AM - 05:00 PM daily",
    travelTips: [
      "Visit in the morning to catch the spectacular rainbow reflecting off the mist.",
      "Wear sturdy non-slip water shoes if you plan to climb up the stairs to the upper levels.",
      "Rent a local cottage or bamboo balsa to enjoy a pristine dining experience by the pool.",
      "Bring water-resistant cases or dry bags for your electronics and cameras."
    ],
    nearbyAttractions: ["Sian Falls", "Hinayagan Cave", "Lake 77"],
    nearbyRestaurants: ["Food in a Box", "Brew Side Cafe"],
    accessibility: "Wheelchair accessible lower viewing deck, paved pathways. Upper tiers require climbing stone steps.",
    coordinates: { lat: 8.1706, lng: 126.2291 },
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Tinuy-an+Falls,+Bislig,+Surigao+del+Sur,+Philippines",
    rating: 4.9
  },
  {
    id: "enchanted-river",
    name: "Hinatuan Enchanted River",
    description: "A world-famous deep, crystal-clear saltwater spring river displaying deep sapphire and turquoise hues, wrapped in legend.",
    longDescription: "Located in neighboring Hinatuan (just 40 minutes from Bislig), the Enchanted River is an absolute must-visit. Its crystal-clear saltwater spring seems to emerge magically from a deep underwater cave system that remains largely unexplored. No one knows exactly where the saltwater comes from. At 12:00 PM daily, the river is cleared of swimmers for the 'Hinatuan Hymn,' during which a school of large fish mysteriously appears from the deep to be fed by park rangers. Swimming is permitted in dedicated safe zones downriver to protect the fragile spring source.",
    category: "Rivers",
    image: "/assets/images/Enchanted River Featured 1.jpg",
    distance: "24 km",
    travelTime: "40 mins",
    difficulty: "Easy",
    bestTime: "11:30 AM - 01:00 PM (for the feeding ritual)",
    entranceFee: "₱100.00 (Adults) / ₱30.00 (Children)",
    openingHours: "07:00 AM - 05:00 PM daily",
    travelTips: [
      "The world-famous fish-feeding ceremony takes place exactly at 12:00 PM. Arrive early to secure a good viewing spot.",
      "To protect the marine ecosystem, standard sunscreen and soaps are prohibited before swimming. Use eco-friendly alternatives.",
      "Life vests are strictly mandatory for all swimming activities and are included or rentable on-site.",
      "Hire a local motorized boat at the mouth of the river to explore nearby islands and coastal seafood stalls."
    ],
    nearbyAttractions: ["Kawa-Kawa Hot Stone Bath", "Hinatuan Cold Spring", "Harip Beach"],
    nearbyRestaurants: ["Fabella Coffee", "Brew Side Cafe"],
    accessibility: "Paved steps with handrails lead down to the water. Floating docks and walkways are highly stable.",
    coordinates: { lat: 8.4357, lng: 126.3683 },
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Hinatuan+Enchanted+River,+Hinatuan,+Surigao+del+Sur,+Philippines",
    rating: 4.8
  },
  {
    id: "kawa-kawa-sa-awog",
    name: "Kawa-kawa sa Awog (Kawa-kawa Falls)",
    description: "Kawa-kawa Falls, located in Bislig, Surigao del Sur, is a captivating natural wonder known for its unique shape, resembling a series of woks or bowls.",
    longDescription: "Kawa-kawa Falls, located in Bislig, Surigao del Sur, is a captivating natural wonder known for its unique shape, resembling a series of woks or bowls. The waterfall flows down from the mountains, creating several natural pools, perfect for swimming and relaxation. The clear, flowing water adds to the serene atmosphere. For thrill-seekers, diving decks offer an exciting way to enjoy the falls. Small cottages are scattered around the area for visitors to rest. Accessible by bus or private vehicle, the falls are reachable via a mostly concrete and passable road, making it an easy and enjoyable destination for nature lovers.",
    category: "Waterfalls",
    image: "/assets/images/kawa-kawa featured 1.webp",
    distance: "28 km",
    travelTime: "45 mins",
    difficulty: "Easy",
    bestTime: "08:00 AM - 04:00 PM (for sunny swimming and diving)",
    entranceFee: "₱20.00 / Cottage rentals range from ₱300.00 to ₱500.00",
    openingHours: "07:00 AM - 05:00 PM daily",
    travelTips: [
      "Bring extra clothes and swimwear as the natural pools are incredibly refreshing and perfect for swimming.",
      "Rent one of the local bamboo cottages to safely keep your belongings and rest between swims.",
      "Try out the designated diving platforms if you're a thrill-seeker, but always check water depth first.",
      "Ensure you bring your own food and refreshments as there are no large restaurants directly at the falls."
    ],
    nearbyAttractions: ["Tinuy-an Falls", "Hinayagan Cave"],
    nearbyRestaurants: ["Brew Side Cafe", "Fabella Coffee"],
    accessibility: "Accessible by bus or private vehicle via a mostly concrete and passable road, with a short walk to the main pools.",
    coordinates: { lat: 8.2450, lng: 126.2300 },
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Kawa-Kawa+Falls,+Bislig,+Surigao+del+Sur,+Philippines",
    rating: 4.7
  },
  {
    id: "hagonoy-island",
    name: "Hagonoy Island",
    description: "An uninhabited tropical island with glistening powdery white sand, swaying coconut palms, and crystal coastal waters.",
    longDescription: "Hagonoy Island is a slice of pure, untouched beach paradise located in the waters of Bislig Bay. This uninhabited sandbar features fine, powdery white sand that shifts gracefully with the seasonal ocean currents. A single stand of coconut palms dominates the center of the island, offering a picturesque shade. The clear waters surrounding the island are rich in marine life, making it a spectacular destination for snorkeling, beach bumming, and dining on fresh seafood caught and cooked on-site by local boatmen.",
    category: "Beaches",
    image: "/assets/images/hagonoy featured 1.jpg",
    distance: "4.5 km (offshore)",
    travelTime: "25 mins boat ride",
    difficulty: "Easy",
    bestTime: "07:00 AM - 02:00 PM (during low to medium tide)",
    entranceFee: "₱20.00 / Boat rentals from Baywalk range from ₱1,500.00 to ₱2,000.00",
    openingHours: "Daylight hours only",
    travelTips: [
      "Rent an outrigger boat (bangka) early in the morning from the Bislig Baywalk pier.",
      "Bring your own snorkel, mask, and reef-safe sunscreen, as there are no commercial shops on the island.",
      "Ask your boat captain to help purchase fresh crabs or fish from passing fishermen to grill on the island.",
      "Pack all waste back with you to preserve the island's strict trash-free policy."
    ],
    nearbyAttractions: ["Bislig Baywalk", "Chocolate Beach"],
    nearbyRestaurants: ["Food in a Box"],
    accessibility: "Requires boarding and disembarking a pump boat directly onto the shallow beach water.",
    coordinates: { lat: 8.2415, lng: 126.3752 },
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Hagonoy+Island,+Bislig,+Surigao+del+Sur,+Philippines",
    rating: 4.7
  },
  {
    id: "hinayagan-cave",
    name: "Hinayagan Cave",
    description: "An enchanting limestone cave with a natural skylight dome that lets sunbeams illuminate an emerald pool.",
    longDescription: "Located in Brgy. San Jose, Bislig City, Hinayagan Cave is a remarkable geological wonder. The name 'Hinayagan' is derived from the Kamayo word for 'illuminated' or 'brightened'. Inside, the cave features a spectacular, open circular limestone dome that acts as a natural ceiling skylight. Around midday, spectacular shafts of golden sunlight pierce through the opening, dramatically illuminating the cave's inner chambers and a tranquil pool of emerald water. The cave is decorated with stunning stalactites, stalagmites, and unique mineral flowstones.",
    category: "Caves",
    image: "/assets/images/Hinayagan Cave Featured 1.jpg",
    distance: "12 km",
    travelTime: "20 mins",
    difficulty: "Moderate",
    bestTime: "11:00 AM - 01:00 PM (for the overhead sunbeam effect)",
    entranceFee: "₱30.00 (includes safety helmet and local guide guide)",
    openingHours: "08:00 AM - 04:00 PM daily",
    travelTips: [
      "Always go with a registered local tour guide guide. Helmets are strictly required inside.",
      "Wear sturdy shoes with good traction, as the cave floor and rocky pathways can be slippery.",
      "Bring a waterproof headlamp or flashlight to inspect the stunning rock formations closely.",
      "Keep silence inside to respect the local bat colonies roosting in the deep crevices."
    ],
    nearbyAttractions: ["Tinuy-an Falls", "Sian Falls"],
    nearbyRestaurants: ["Brew Side Cafe"],
    accessibility: "Requires trekking down a natural forest path and entering a semi-steep cave opening. Slippery surfaces.",
    coordinates: { lat: 8.1611, lng: 126.2625 },
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Hinayagan+Cave,+Bislig,+Surigao+del+Sur,+Philippines",
    rating: 4.5
  },
  {
    id: "lake-77",
    name: "Lake 77",
    description: "A tranquil, mirror-like eco-lake bordered by lush forest canopies, perfect for calming kayaking and bird-watching.",
    longDescription: "Lake 77 is a serene freshwater lake tucked deep within the lush green woodlands of Brgy. Sibaroy, Bislig City. Originally established during the early logging era, this hidden lake has evolved into a flourishing, peaceful sanctuary for native birds and water plants. The water is remarkably still, reflecting the emerald forest canopy like a perfect mirror. Visitors can rent manual kayaks, stand-up paddleboards, or cozy floating bamboo cottages to spend a relaxing day disconnected from the digital world.",
    category: "Parks",
    image: "/assets/images/Lake 77 Featured 1.jpg",
    distance: "15 km",
    travelTime: "25 mins",
    difficulty: "Easy",
    bestTime: "06:00 AM - 09:00 AM (ideal for birdwatching) or late afternoon",
    entranceFee: "₱30.00 / Kayak rental ₱100.00 per hour",
    openingHours: "07:00 AM - 05:00 PM daily",
    travelTips: [
      "Bring binoculars if you enjoy bird-watching; you might spot unique Philippine hornbills and kingfishers.",
      "Rent a floating bamboo raft to enjoy a peaceful, quiet picnic in the middle of the lake.",
      "The road leading to the lake can be muddy after rainfall; a sturdy 4-wheel drive or local habal-habal is recommended.",
      "Perfect spot for meditation, reading, and enjoying untouched forest therapy."
    ],
    nearbyAttractions: ["Tinuy-an Falls", "Forester's Park"],
    nearbyRestaurants: ["Fabella Coffee"],
    accessibility: "Flat paths lead directly to the lakeside boarding deck. Easy access for all age groups.",
    coordinates: { lat: 8.1834, lng: 126.2081 },
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Lake+77,+Bislig,+Surigao+del+Sur,+Philippines",
    rating: 4.6
  }
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: "food-in-a-box",
    name: "Food in a Box",
    description: "A hip, contemporary restaurant hub offering magnificent Kamayo-style seafood platters and modern Filipino favorites.",
    category: "Seafood",
    image: "/assets/images/Food in a Box featured 1.jpg",
    specialty: ["Kamayo Mud Crabs in Garlic-Butter", "Sizzling Squid Sisig", "Pristine Bislig Tuna Sashimi"],
    priceRange: "₱250 - ₱600 per person",
    contact: "+63 917 888 1234",
    socialMedia: "facebook.com/foodinaboxbislig",
    website: "https://food-in-a-box-fiab-114507837221.asia-southeast1.run.app",
    operatingHours: "10:00 AM - 10:00 PM daily",
    coordinates: { lat: 8.2114, lng: 126.3488 },
    mapUrl: "https://www.google.com/maps/search/Food+in+a+Box+Bislig",
    rating: 4.7
  },
  {
    id: "brew-side-cafe",
    name: "Brew Side Cafe",
    description: "The favorite local specialty cafe, known for its cold brews, aesthetic wooden interiors, and gourmet artisan pastries.",
    category: "Cafe",
    image: "/assets/images/brew side cafe featured 1.jpg",
    specialty: ["Mindanao Highland Cold Brew", "Tablea Chocolate Lava Cake", "Salted Caramel Spanish Latte"],
    priceRange: "₱120 - ₱250 per person",
    contact: "+63 908 777 5678",
    socialMedia: "facebook.com/breysidecafebislig",
    website: "https://brewsidebislig.com",
    operatingHours: "08:00 AM - 11:00 PM daily",
    coordinates: { lat: 8.2098, lng: 126.3512 },
    mapUrl: "https://www.google.com/maps/search/Brew+Side+Cafe+Bislig",
    rating: 4.8
  },
  {
    id: "fabella-coffee",
    name: "Fabella Coffee",
    description: "An elegant, premium cafe and roastery showcasing single-origin Mindanao Arabica and local Kamayo snacks.",
    category: "Cafe",
    image: "/assets/images/Fabella Cafe Featured 1.jpg",
    specialty: ["Drip Mount Apo Arabica", "Kamayo Cassava Bibingka", "Ice Cream Waffle Sandwich"],
    priceRange: "₱150 - ₱300 per person",
    contact: "+63 919 666 4321",
    socialMedia: "instagram.com/fabellacoffee",
    website: "https://fabellacoffee.ph",
    operatingHours: "07:00 AM - 10:00 PM daily",
    coordinates: { lat: 8.2081, lng: 126.3533 },
    mapUrl: "https://www.google.com/maps/search/Fabella+Coffee+Bislig",
    rating: 4.9
  }
];

export const ACCOMMODATIONS: Accommodation[] = [
  {
    id: "harip-beach",
    name: "Harip Beach Resort",
    description: "An eco-luxury beachfront resort offering stunning wooden cottages, surfing waves, and coconut tree swings.",
    category: "Beachfront",
    image: "/assets/images/Harip Resort Featured 1.webp",
    priceRange: "₱2,500 - ₱6,000 per night",
    amenities: ["Oceanfront View", "Infinity Hammocks", "Surfboard Rentals", "Outdoor Bamboo Showers", "Free WiFi", "Beachside Barbecue Grill"],
    contact: "+63 920 111 9999",
    socialMedia: "facebook.com/haripbeachresort",
    website: "https://harip-beach-resort-114507837221.asia-southeast1.run.app",
    operatingHours: "24/7 Front Desk / Check-in 2:00 PM",
    coordinates: { lat: 8.4412, lng: 126.4215 },
    mapUrl: "https://www.google.com/maps/search/Harip+Beach+Resort",
    rating: 4.7
  },
  {
    id: "hinatuan-cold-spring",
    name: "Hinatuan Cold Spring Resort",
    description: "A serene, natural freshwater spring resort surrounded by forest canopies, offering refreshing ice-cold dips.",
    category: "Eco Lodge",
    image: "/assets/images/Enchanted River Featured 2.jpg",
    priceRange: "₱1,200 - ₱3,500 per night (Cabins and Cottages available)",
    amenities: ["Natural Spring Pool", "Bamboo Floating Cottages", "Native Karaoke Pavilions", "Campgrounds", "On-site Local Canteen"],
    contact: "+63 930 444 8888",
    socialMedia: "facebook.com/hinatuancoldspring",
    website: "https://hinatuancoldspring.com",
    operatingHours: "08:00 AM - 08:00 PM for day-trips, 24/7 for overnight cabins",
    coordinates: { lat: 8.4114, lng: 126.3524 },
    mapUrl: "https://www.google.com/maps/search/Hinatuan+Cold+Spring+Resort",
    rating: 4.5
  },
  {
    id: "kawa-kawa",
    name: "Kawa-Kawa Jungle Bath & Lodge",
    description: "An authentic, nature-inspired eco-lodge featuring traditional giant hot stone baths, set in a peaceful rainforest valley.",
    category: "Eco Lodge",
    image: "/assets/images/kawa-kawa featured 1.webp",
    priceRange: "₱1,800 - ₱4,000 per night",
    amenities: ["Traditional Giant Kawa Hot Baths", "Forest Canopy Boardwalks", "Organic Herbal Tea Garden", "Yoga & Meditation Shala", "Local Tour Guides"],
    contact: "+63 940 555 7777",
    socialMedia: "instagram.com/kawakawajungle",
    website: "https://kawakawajungle.com",
    operatingHours: "08:00 AM - 09:00 PM",
    coordinates: { lat: 8.4231, lng: 126.3611 },
    mapUrl: "https://www.google.com/maps/search/Kawa-Kawa+Hot+Stone+Bath+Hinatuan",
    rating: 4.8
  }
];

export const EVENTS: TourismEvent[] = [
  {
    id: "karawasan",
    title: "Karawasan Festival",
    subtitle: "The Grand Crab Harvest Celebration of the Kamayo Tribe",
    date: "September 17 - 18",
    dateRange: "September 17–18, 2025",
    month: "SEP",
    day: "17",
    year: "2025",
    description: "The primary cultural festival of Bislig City, celebrated through vibrant, nature-inspired street dancing, ethnic chants, and indigenous games representing the Kamayo tribe's appreciation of crab harvests.",
    type: "Festival",
    image: "/assets/images/Harip Featured 2.jpg",
    heroImage: "/assets/images/Harip Featured 2.jpg",
    gallery: [
      "/assets/images/Harip Featured 3.jpg",
      "/assets/images/Harip Resort Featured 1.webp",
      "/assets/images/Hinayagan Cave Featured 2.jpg"
    ],
    location: "Bislig City Plaza & Baywalk Park, Bislig City",
    organizer: "Bislig City Government & Department of Tourism, Region XIII",
    overview: "The Karawasan Festival is the crown jewel of Bislig City's cultural calendar — a dazzling two-day celebration held every September 17–18 that transforms the city into a vivid tapestry of indigenous color, music, and movement. Named after the Kamayo word for the native blue swimming crab (Portunus pelagicus), which thrives in the waters of Bislig Bay and the rivers that flow to it, the festival is both a thanksgiving rite and a proud declaration of Bislig's cultural identity. Thousands of locals, performers, and tourists from across Mindanao and beyond gather to witness elaborate street-dancing contingents, tribal costumes adorned with shells and woven rattan, live gong percussion ensembles, and a festive trade fair showcasing the best of Surigao del Sur's agricultural and seafood products.",
    history: "The roots of Karawasan stretch back to the pre-colonial era when the indigenous Kamayo people of the Bislig River basin performed ritual harvest dances to honor the sea spirits (Diwata sa Dagat) before each communal crab-harvesting season. Elders would lead the village in a night-long ceremony of chanting, torch-lit dances, and offerings of woven gifts placed at the river's mouth. When Spanish missionaries arrived in the 17th century, they incorporated elements of the feast into the Catholic calendar, blending indigenous and Christian celebration. The formal festival as we know it today was institutionalized in 1996 under then-Mayor Edilberto Uy to coincide with Bislig City Charter Day, giving the festival a permanent civic identity and attracting funding for larger, more organized contingents. Over three decades it has grown from a modest barangay affair to a province-wide spectacle featuring over 2,000 performers across competing street-dancing groups from all barangays.",
    highlights: [
      "Grand Street-Dancing Parade along Quezon Avenue featuring 20+ barangay contingents in full tribal regalia",
      "\"Sayaw sa Karawasan\" — the signature crab-mimicking dance choreography judged for creativity and cultural authenticity",
      "Live Kulintang (bronze gong) and Agung ensemble performances at the Open-Air Amphitheater",
      "Karawasan Cook-Off — live seafood cooking competition using locally-caught crabs and Bislig Bay seafood",
      "Tribal Artisan Market with handwoven baskets, Kamayo pottery, and native jewelry from surrounding villages",
      "Fireworks display over Bislig Bay on the evening of September 18",
      "Search for Mutya ng Karawasan — Miss Bislig pageant featuring candidates in traditional Kamayo attire"
    ],
    schedule: [
      { time: "Day 1 — 6:00 AM", activity: "Fluvial Procession along Bislig River — offerings of flowers and native goods to the sea" },
      { time: "Day 1 — 9:00 AM", activity: "Opening Ceremonies, raising of the Festival Colors at the City Plaza" },
      { time: "Day 1 — 10:00 AM", activity: "Grand Street-Dancing Parade — barangay contingents in full Kamayo tribal costume" },
      { time: "Day 1 — 2:00 PM", activity: "Karawasan Cook-Off Competition at the Baywalk Pavilion" },
      { time: "Day 1 — 6:00 PM", activity: "Kulintang Night — live traditional gong music & cultural variety show" },
      { time: "Day 2 — 8:00 AM", activity: "Sports Tournament (Dragon Boat & Outrigger Racing in Bislig Bay)" },
      { time: "Day 2 — 12:00 PM", activity: "Bislig City Charter Day Program — civic awards & recognition rites" },
      { time: "Day 2 — 7:00 PM", activity: "Search for Mutya ng Karawasan Pageant Night & Grand Concert" },
      { time: "Day 2 — 9:00 PM", activity: "Fireworks Finale over Bislig Bay" }
    ],
    tips: [
      "Arrive by 8 AM on Day 1 to secure front-row viewing spots along Quezon Avenue before the parade begins.",
      "Wear lightweight breathable clothing — September heat and humidity can be intense especially near the bay.",
      "Book accommodations at least 3–4 weeks in advance; hotels along the Baywalk fill up quickly during festival week.",
      "Try the festival's iconic \"sinuglaw\" (grilled tuna mixed with raw crab ceviche) from street vendors — it is a Karawasan tradition.",
      "Bring cash for the artisan market; most vendors do not accept digital payments.",
      "Respect tribal performers — ask permission before photographing close-up during the procession."
    ],
    tags: ["Festival", "Culture", "Heritage", "Kamayo", "Street Dancing", "September"]
  },
  {
    id: "charter-day",
    title: "Bislig City Charter Day",
    subtitle: "Celebrating the City's Founding & Identity Since 2000",
    date: "September 18",
    dateRange: "September 18, 2025",
    month: "SEP",
    day: "18",
    year: "2025",
    description: "A grand anniversary celebration featuring dynamic agricultural trade fairs, coastal regattas, musical concerts, and the highly anticipated Search for Miss Bislig — commemorating the city's official charter.",
    type: "Community",
    image: "/assets/images/Harip Resort Featured 1.webp",
    heroImage: "/assets/images/Harip Resort Featured 1.webp",
    gallery: [
      "/assets/images/Harip Featured 2.jpg",
      "/assets/images/bislig sports center.jpg",
      "/assets/images/Bislig City Hall.jpg"
    ],
    location: "Bislig City Hall Grounds, Plaza & Bislig Bay Area",
    organizer: "Office of the City Mayor, Bislig City",
    overview: "Bislig City Charter Day on September 18 is the annual commemoration of the city's elevation from municipality to city status — a milestone that reshaped the political, economic, and cultural landscape of Surigao del Sur. The celebration is a multi-event civic showcase that brings together government officials, barangay leaders, civil society, and thousands of residents in a shared expression of civic pride. From trade fairs displaying the city's agricultural bounty to regattas racing across the sparkling waters of Bislig Bay, Charter Day is as much a festival of progress as it is of heritage. Musical concerts, recognition ceremonies, and the beloved Miss Bislig pageant round out a packed day of celebration that typically runs from dawn to midnight.",
    history: "Bislig's history as a chartered city is relatively young but deeply meaningful. The municipality of Bislig was formally converted into a city by Republic Act No. 8804, signed into law on August 16, 2000, by President Joseph Estrada, and ratified by the people of Bislig in a plebiscite on October 28, 2000. However, the official Charter Day falls on September 18 to commemorate the date the city government formally began operations. Before cityhood, Bislig was a thriving timber town built largely around the Paper Industries Corporation of the Philippines (PICOP), one of the largest wood-pulp complexes in Asia. When the timber industry declined, Bislig reinvented itself as an emerging eco-tourism and agri-fishery hub — a transformation that Charter Day celebrations have increasingly highlighted in recent years with agricultural fairs, seafood festivals, and investor forums.",
    highlights: [
      "Agricultural & Aquaculture Trade Fair — booths from all 25 barangays showcasing Bislig's finest farm and sea produce",
      "Bislig Bay Regatta — traditional outrigger (bangka) racing competition open to all barangay teams",
      "DOT-accredited Tourism Investment Forum — showcasing new resort, eco-tourism, and hospitality opportunities",
      "Cultural Variety Show — performances by local schools and universities featuring Bislig folk music and dances",
      "Search for Miss Bislig — the city's premier beauty and intelligence pageant, broadcast live on local radio",
      "Public awards ceremony recognizing outstanding citizens, barangay officials, and young achievers",
      "Evening Grand Concert featuring OPM (Original Pilipino Music) artists"
    ],
    schedule: [
      { time: "6:00 AM", activity: "Flag Raising Ceremony at Bislig City Hall with full civic honors" },
      { time: "8:00 AM", activity: "Opening of Agricultural & Aquaculture Trade Fair at the Civic Center Grounds" },
      { time: "10:00 AM", activity: "Bislig Bay Regatta — outrigger races across designated bay course" },
      { time: "12:00 PM", activity: "Official Charter Day Program — guest speakers, civic awards, and recognition rites" },
      { time: "2:00 PM", activity: "Tourism Investment Forum at the City Hall Multi-Purpose Hall" },
      { time: "4:00 PM", activity: "Cultural Show & Talent Competition — schools and community groups" },
      { time: "7:00 PM", activity: "Miss Bislig Pageant Night at the City Plaza Grandstand" },
      { time: "9:00 PM", activity: "Grand Concert & Street Party along Baywalk" }
    ],
    tips: [
      "The Agricultural Trade Fair is the best place to buy fresh, local Bislig products at excellent prices — bring an extra bag.",
      "The Regatta is best viewed from the Baywalk seawall or hire a small banca for a water-level vantage point.",
      "Charter Day falls on the same day as Karawasan Festival Day 2 — plan your schedule to enjoy both events.",
      "City Hall and barangay offices may have reduced service hours — plan any official business a day before.",
      "Parking near the plaza fills up fast; consider arriving by tricycle from your hotel.",
      "The evening concert draws large crowds — stake out a good spot before the pageant ends."
    ],
    tags: ["Civic", "Culture", "Community", "Cityhood", "September", "Trade Fair"]
  },
  {
    id: "tinuyan-swim",
    title: "Tinuy-an Eco Trail Marathon",
    subtitle: "Race Through the Rainforest to the Base of the Philippines' Widest Waterfall",
    date: "May 24",
    dateRange: "May 24, 2025",
    month: "MAY",
    day: "24",
    year: "2025",
    description: "An annual sports-tourism marathon that tests participants' stamina along rugged tropical rainforest terrains, finishing directly at the base pool of the magnificent Tinuy-an Falls — the widest curtain waterfall in the Philippines.",
    type: "Sports",
    image: "/assets/images/Tinuy.an Featured 2.webp",
    heroImage: "/assets/images/Tinuy.an Featured 3.webp",
    gallery: [
      "/assets/images/Tinuy.an Featured 1.webp",
      "/assets/images/Tinuy.an Featured 2.webp",
      "/assets/images/Lake 77 Featured 1.jpg"
    ],
    location: "Starting Point: Barangay Burboanan Trailhead → Finish: Tinuy-an Falls Viewing Deck",
    organizer: "Bislig City Sports Development & Tourism Office in partnership with Philippine Athletics Track & Field Association (PATAFA)",
    overview: "The Tinuy-an Eco Trail Marathon is one of the most breathtaking trail-running events in Mindanao — a race unlike any other where the finish line is the base of the Philippines' most spectacular waterfall. Held annually in May, the marathon draws hundreds of athletes and adventure enthusiasts from across the Philippines and abroad who come not just to compete but to experience the raw, humbling beauty of Bislig's rainforest trails. The 21-kilometer primary route winds through old-growth dipterocarp forest, elevated ridge trails with panoramic views of the Bislig River valley, and finishes at the iconic three-tiered curtain cascade of Tinuy-an Falls where participants are rewarded with a natural plunge-pool swim and the roar of 95 meters of falling water.",
    history: "The marathon was first organized in 2009 by a group of Bislig-based trail runners who wanted to create an adventure sports event that would put the city on the eco-tourism map. The inaugural race had just 87 participants, mostly local athletes, but the striking finish-line imagery — runners emerging from jungle trails into the mist of Tinuy-an Falls — quickly went viral on early Philippine social media, attracting national attention. By 2015, the event had grown to over 500 participants and earned recognition from the Philippine Sports Commission as one of the Top 10 Most Scenic Trail Running Events in the country. The COVID-19 pandemic forced a hiatus from 2020–2021, but the event returned stronger in 2022 with a new environmental component — participants are required to carry a small trash bag and collect litter along the trail as part of the Bislig City \"Race Clean\" initiative.",
    highlights: [
      "3K Fun Run category — family-friendly entry-level trail through the forest edges, open to all ages",
      "10K Trail Run — intermediate mountain category crossing the elevated Bislig Ridge Trail",
      "21K Half-Marathon — the signature \"Falls Finish\" route through primary-growth dipterocarp rainforest",
      "Post-race swimming at the natural plunge pool at the base of Tinuy-an Falls",
      "\"Race Clean\" eco-initiative — prizes awarded to the team collecting the most litter along the trail",
      "Finisher medals and custom shirts made from locally-woven Kamayo cloth",
      "Adventure photography stations along the route capturing participants against the jungle canopy"
    ],
    schedule: [
      { time: "4:00 AM", activity: "Race Day Registration & Kit Collection at Burboanan Trailhead Base Camp" },
      { time: "5:00 AM", activity: "21K Half-Marathon Gun Start — elite and open categories" },
      { time: "5:30 AM", activity: "10K Trail Run Gun Start" },
      { time: "6:30 AM", activity: "3K Fun Run Gun Start — families and community participants" },
      { time: "7:00 AM", activity: "First elite finishers expected at Tinuy-an Falls finish line" },
      { time: "9:00 AM", activity: "Final cutoff for all categories — post-race swimming open" },
      { time: "10:00 AM", activity: "Awarding Ceremony at the Tinuy-an Falls Eco Park Pavilion" },
      { time: "11:00 AM", activity: "Race Clean Eco Awards — top trash-collecting teams recognized" },
      { time: "12:00 PM", activity: "Free lunch for all participants (local catering by Bislig City vendors)" }
    ],
    tips: [
      "Register early — the 21K category fills up fast; registration typically opens 3 months before the event.",
      "Train specifically for trail running; the route includes steep ascents and root-covered paths that are very different from road running.",
      "Bring waterproof trail shoes — the river crossings and forested sections are consistently muddy regardless of weather.",
      "Pack a lightweight waterproof dry bag for your phone and documents; the finish involves spray from the falls.",
      "Carry electrolyte supplements; the tropical heat and humidity along jungle sections are intense even in early morning.",
      "Book accommodation in Bislig City the night before — the 4 AM start makes same-day travel from other cities impractical.",
      "Stay for the afternoon after the race — a visit to the top tier of Tinuy-an Falls by bamboo raft is unforgettable."
    ],
    tags: ["Sports", "Trail Running", "Eco-Tourism", "Tinuy-an Falls", "Adventure", "May"]
  }
];


export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Dawn over Tinuy-an Cascades",
    category: "Waterfalls",
    image: "/assets/images/Tinuy.an Featured 3.webp",
    author: "Romer Amper"
  },
  {
    id: "gal-2",
    title: "Mystical Deep Sapphire Blue",
    category: "Rivers",
    image: "/assets/images/Enchanted River Featured 2.jpg",
    author: "Alvin Santos"
  },
  {
    id: "gal-3",
    title: "Bislig Bay Sunrise Glow",
    category: "Drone",
    image: "/assets/images/Harip Featured 3.jpg",
    author: "Elena Cruz"
  },
  {
    id: "gal-4",
    title: "White Sandbar of Hagonoy Island",
    category: "Beaches",
    image: "/assets/images/hagonoy featured 2.jpg",
    author: "Mark Diaz"
  },
  {
    id: "gal-5",
    title: "Traditional Kamayo Tribal Headdress",
    category: "People",
    image: "/assets/images/Harip Resort Featured 1.webp",
    author: "Lani Perez"
  },
  {
    id: "gal-6",
    title: "Delicious Garlic-Butter Mud Crabs",
    category: "Food",
    image: "/assets/images/Food in a Box featured 1.jpg",
    author: "Chef Mike"
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "Ultimate 3-Day Bislig City Eco-Adventure Itinerary",
    excerpt: "Discover the best way to maximize your weekend in Bislig, from chasing morning rainbows at Tinuy-an Falls to swimming with mystical fish at the Enchanted River.",
    content: "Planning a trip to the eastern coast of Mindanao? Bislig City, together with the nearby town of Hinatuan, forms a powerhouse eco-tourism circuit that you shouldn't miss. On your first day, start early at 8:00 AM to catch the magnificent morning rainbow at Tinuy-an Falls. After enjoying a bamboo balsa ride, enjoy lunch at Brew Side Cafe. For Day 2, visit the magical Hinatuan Enchanted River just in time for the 12:00 PM fish feeding ritual. Spend your final day island hopping on the powdery white sand of Hagonoy Island.",
    date: "June 25, 2026",
    author: "Tourism Officer",
    readTime: "5 min read",
    category: "Travel Guide",
    image: "/assets/images/Tinuy.an Featured 1.webp"
  },
  {
    id: "blog-2",
    title: "The Legends of the Enchanted River: Myth vs Science",
    excerpt: "Why is the Enchanted River saltwater? Why do the fish only appear when the hymn plays? Dive into the fascinating mysteries and scientific theories.",
    content: "For generations, the local Kamayo people have passed down legends of spirits, fairies, and mermaids guarding the deep turquoise pool of Hinatuan. Legend has it that the unique sapphire-blue color was created by fairies stirring jade and sapphires into the water. Scientifically, the river is a unique estuarine karst spring, where an underwater limestone cave system feeds clean saltwater from the Pacific Ocean directly into the basin. The daily fish feeding remains an incredible spectacle of animal behavior.",
    date: "May 18, 2026",
    author: "Cultural Heritage Specialist",
    readTime: "7 min read",
    category: "Hidden Gem",
    image: "/assets/images/Enchanted River Featured 3.jpg"
  }
];

export const FAQS: FAQ[] = [
  {
    question: "How do I travel to Bislig City?",
    answer: "The nearest major airports are Francisco Bangoy International Airport (Davao City) and Bancasi Airport (Butuan City). From Davao or Butuan, you can take a comfortable air-conditioned passenger bus (such as Bachelor Express) or hire a private van directly to Bislig City (Mangagoy Terminal). The road trip takes approximately 4-5 hours from Butuan, and 5-6 hours from Davao.",
    category: "Transportation"
  },
  {
    question: "When is the best season to visit Tinuy-an Falls?",
    answer: "Swimming is strictly prohibited in the main deep blue pool area to protect the extremely fragile marine ecosystem and cave structures. However, a beautifully designated and secure swimming zone is open just 100 meters downriver, where you can enjoy the same crystal-clear saltwater flow.",
    category: "Safety & Rules"
  }
];

export const ESTABLISHMENTS: Establishment[] = [
  {
    id: "gaisano-bislig",
    name: "Gaisano Capital Bislig",
    description: "The premier shopping mall in Bislig City, offering department stores, a supermarket, food outlets, and retail shopping.",
    longDescription: "Gaisano Capital Bislig serves as the primary modern retail center for locals and visiting tourists in Surigao del Sur. Strategically located along the highway in Brgy. Cumawas, it features a comprehensive supermarket for grocery needs, a department store offering apparel, electronics, and home items, plus a food court housing popular national chains. It is the perfect stop to buy supplies, withdraw cash from multiple stable ATMs, or take a cool break in its fully air-conditioned spaces.",
    category: "Shops & Malls",
    image: "/assets/images/Gaisano Capital Bislig.jpg",
    location: "National Highway, Brgy. Cumawas, Bislig City",
    contact: "+63 86 853 1234",
    socialMedia: "facebook.com/gaisanocapitalbislig",
    website: "https://www.gaisanocapital.com",
    operatingHours: "09:00 AM - 08:30 PM daily",
    coordinates: { lat: 8.2125, lng: 126.3578 },
    mapUrl: "https://www.google.com/maps/search/Gaisano+Capital+Bislig",
    rating: 4.4
  },
  {
    id: "mangagoy-market",
    name: "Mangagoy Public Market & Commercial Center",
    description: "The bustling commercial heart of Bislig, where you can buy fresh seafood, dried fish (sapan-sapan), local fruits, and traditional Kamayo delicacies.",
    longDescription: "If you want to experience the authentic local lifestyle, the Mangagoy Public Market is a must-visit. Renowned for its rich seafood section, you can purchase fresh-off-the-boat yellowfin tuna, mud crabs, and sea urchins at very affordable prices. The dry section features the famous Kamayo dried fish locally called 'sapan-sapan' or 'tuyo,' which make excellent souvenirs (pasalubong). Local vendors are extremely welcoming and happy to share traditional cooking tips.",
    category: "Shops & Malls",
    image: "/assets/images/Mangagoy public market.webp",
    location: "Espiritu Street, Brgy. Mangagoy, Bislig City",
    contact: "N/A (Public Market Authority)",
    socialMedia: "N/A",
    website: "",
    operatingHours: "04:00 AM - 07:00 PM daily",
    coordinates: { lat: 8.2085, lng: 126.3508 },
    mapUrl: "https://www.google.com/maps/search/Mangagoy+Public+Market",
    rating: 4.5
  },
  {
    id: "7eleven-mangagoy",
    name: "7-Eleven Mangagoy",
    description: "Convenient 24/7 stop for snacks, drinks, basic travel supplies, and automated cash withdrawals in the city center.",
    longDescription: "Located at the heart of the commercial hub in Brgy. Mangagoy, this 7-Eleven store provides reliable 24-hour service for tourists and night travelers. Stocked with ready-to-eat meals, ice-cold beverages, basic toiletries, and emergency phone-load services. It also features a secure in-store ATM, which is highly valuable since commercial banks in the area can occasionally experience long lines.",
    category: "Convenience Stores",
    image: "/assets/images/7 eleven.jpg",
    location: "Espiritu Street, Brgy. Mangagoy, Bislig City",
    contact: "+63 2 8711 0711",
    socialMedia: "facebook.com/711philippines",
    website: "https://www.7-eleven.com.ph",
    operatingHours: "24/7 daily",
    coordinates: { lat: 8.2091, lng: 126.3514 },
    mapUrl: "https://www.google.com/maps/search/7-Eleven+Mangagoy+Bislig",
    rating: 4.2
  },
  {
    id: "sports-complex-courts",
    name: "Bislig City Sports Complex (Pickleball & Tennis)",
    description: "A multi-purpose sports facility featuring modern indoor and outdoor pickleball courts, tennis courts, and basketball fields.",
    longDescription: "The Bislig City Sports Complex is a premium hub for local sports enthusiasts and active visitors. It features newly surfaced, dedicated pickleball courts with tournament-grade net fittings and nighttime lighting. It is highly popular during late afternoons. Guests can rent paddles and balls on-site for a minimal fee, or participate in friendly community games. The complex also hosts tennis courts and standard indoor basketball arenas.",
    category: "Sports & Recreation",
    image: "/assets/images/bislig sports center.jpg",
    location: "Brgy. Poblacion, Bislig City",
    contact: "+63 86 853 6000 (City Sports Office)",
    socialMedia: "facebook.com/bisligcitysports",
    website: "https://bislig.gov.ph/services/sports-complex",
    operatingHours: "05:00 AM - 09:00 PM daily",
    coordinates: { lat: 8.2198, lng: 126.3633 },
    mapUrl: "https://www.google.com/maps/search/Bislig+City+Sports+Complex",
    rating: 4.6
  },
  {
    id: "lawigan-surf-point",
    name: "Lawigan Surf Point",
    description: "An advanced reef break point offering strong, hollow waves for experienced surfers during the northeast monsoon (Amihan) season.",
    longDescription: "Lawigan Surf Point is a hidden gem for seasoned wave riders looking for a challenge in Bislig. Situated further out along the coastal headlands of Brgy. Lawigan, this surf point features a rocky bottom reef break that produces fast, powerful, and hollow right-hand waves. Best visited during early mornings when offshore winds shape the swells beautifully. There are no commercial structures here, offering surfers a raw, wild, and untouched surfing experience in pristine Pacific waters.",
    category: "Surfing & Beaches",
    image: "/assets/images/Lawigan Surf point.jpg",
    location: "Coastal Highway, Brgy. Lawigan, Bislig City",
    contact: "N/A",
    socialMedia: "facebook.com/lawigansurfers",
    website: "",
    operatingHours: "Daylight hours only",
    coordinates: { lat: 8.1678, lng: 126.4112 },
    mapUrl: "https://www.google.com/maps/search/Lawigan+Bislig+Surigao+del+Sur",
    rating: 4.7
  },
  {
    id: "bislig-district-hospital",
    name: "Bislig District Hospital",
    description: "A primary public healthcare facility providing emergency services, medical checks, and patient care for visitors and residents.",
    longDescription: "The Bislig District Hospital is the primary medical facility in the region, offering 24-hour emergency response services, clinical consultations, laboratory diagnostics, and inpatient care. Strategically situated along the main highway, it is equipped to handle standard medical requirements and tourism-related emergencies (such as minor surf injuries or travel sickness) with dedicated staff.",
    category: "Services & Others",
    image: "/assets/images/bislig district hospital.jpg",
    location: "National Highway, Brgy. Caramcam, Bislig City",
    contact: "+63 86 853 2214",
    socialMedia: "N/A",
    website: "https://doh.gov.ph/hospital/bislig-district-hospital",
    operatingHours: "24/7 (Emergency) / 08:00 AM - 05:00 PM (OPD)",
    coordinates: { lat: 8.2162, lng: 126.3564 },
    mapUrl: "https://www.google.com/maps/search/Bislig+District+Hospital",
    rating: 4.1
  },
  {
    id: "petron-mangagoy",
    name: "Petron Station - Mangagoy",
    description: "Full-service gas station equipped with clean restrooms, a small convenience store, air supply, and car diagnostic assistance.",
    longDescription: "Petron Mangagoy is a vital stopover for motorists and road-tripping tourists. Located at the entryway of the commercial center, it offers high-quality fuels, clean and modern public toilets, air pressure machines for tires, and a small convenience store. The station also features a mechanic bay offering basic oil changes and tire repair support.",
    category: "Services & Others",
    image: "/assets/images/Petron Mangagoy.webp",
    location: "National Highway, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 4567",
    socialMedia: "facebook.com/petroncorporation",
    website: "https://www.petron.com",
    operatingHours: "05:00 AM - 11:00 PM daily",
    coordinates: { lat: 8.2064, lng: 126.3472 },
    mapUrl: "https://www.google.com/maps/search/Petron+Mangagoy+Bislig",
    rating: 4.3
  },
  {
    id: "d-vet-yard",
    name: "D Vet Yard",
    description: "A trusted local veterinary clinic offering vaccinations, check-ups, pet foods, and health care for dogs, cats, and small animals.",
    longDescription: "D Vet Yard is a premier private veterinary clinic in Bislig City, known for its professional and compassionate care for household pets. Strategically located at the Japus Building on Espiritu Street, it offers routine checkups, deworming, surgical procedures, and standard vaccination schedules. The clinic also features a small pet shop corner stocked with quality pet food, vitamins, and hygiene supplies.",
    category: "Services & Others",
    image: "/assets/images/d vet yard.jpg",
    location: "Japus Bldg, Espiritu St, Brgy. Mangagoy, Bislig City",
    contact: "+63 920 555 1234",
    socialMedia: "facebook.com/dvetyardbislig",
    website: "",
    operatingHours: "08:30 AM - 05:30 PM (Monday to Saturday)",
    coordinates: { lat: 8.2093, lng: 126.3521 },
    mapUrl: "https://www.google.com/maps/search/D+Vet+Yard+Bislig",
    rating: 4.8
  },
  {
    id: "mercury-drug-mangagoy",
    name: "Mercury Drug - Mangagoy",
    description: "The primary 24/7 national pharmacy chain branch in Bislig, providing prescription medications, wellness products, and basic conveniences.",
    longDescription: "Mercury Drug is the most trusted and fully stocked drugstore in Bislig City. Conveniently located on Espiritu Street in the commercial district of Mangagoy, it offers a complete range of prescription drugs, over-the-counter medicines, medical devices, baby care essentials, and nutritional supplements. With standby pharmacists on duty, it is the primary stop for health and emergency medical purchases.",
    category: "Services & Others",
    image: "/assets/images/mercury drug.png",
    location: "Espiritu St, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 1122",
    socialMedia: "facebook.com/mercurydrugcorporation",
    website: "https://www.mercurydrug.com",
    operatingHours: "24/7 daily",
    coordinates: { lat: 8.2088, lng: 126.3512 },
    mapUrl: "https://www.google.com/maps/search/Mercury+Drug+Mangagoy+Bislig",
    rating: 4.7
  },
  {
    id: "tgp-mangagoy",
    name: "The Generics Pharmacy (TGP)",
    description: "Providing high-quality and highly affordable generic medicines, vitamins, and healthcare supplements to the Bislig community.",
    longDescription: "TGP (The Generics Pharmacy) on Abarca Street offers highly cost-effective generic alternatives to brand-name medications. Known for its affordable pricing and extensive stock of maintenance medicines, pain relief tablets, and vitamins, it is a highly valued community establishment helping local families and travelers access budget-friendly healthcare.",
    category: "Services & Others",
    image: "/assets/images/generic pharmacy.jpg",
    location: "Abarca St, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 3344",
    socialMedia: "facebook.com/tgppharma",
    website: "https://tgp.com.ph",
    operatingHours: "08:00 AM - 07:00 PM daily",
    coordinates: { lat: 8.2096, lng: 126.3503 },
    mapUrl: "https://www.google.com/maps/search/The+Generics+Pharmacy+Mangagoy+Bislig",
    rating: 4.4
  },
  {
    id: "kinilaw-king-bislig",
    name: "Kinilaw King - Bislig",
    description: "Famous local seafood restaurant known for serving the best fresh 'Kinilaw' (Mindanao-style raw tuna ceviche), grilled fish, and seafood platters.",
    longDescription: "Kinilaw King is a culinary landmark in Bislig City, celebrating the rich marine harvest of Mindanao. It is widely famous for its 'Kinilaw'—fresh raw yellowfin tuna cubed and cured in local coconut vinegar, ginger, onions, chilies, and tabon-tabon fruit. The restaurant also serves a mouthwatering selection of grilled squid, buttered crabs, and fresh seafood soup, providing a truly local dining experience.",
    category: "Dining & Cafes",
    image: "/assets/images/kinilaw king bislig.jpg",
    location: "Espiritu St, Brgy. Mangagoy, Bislig City",
    contact: "+63 917 111 2233",
    socialMedia: "facebook.com/kinilawkingbislig",
    website: "",
    operatingHours: "10:30 AM - 09:30 PM daily",
    coordinates: { lat: 8.2081, lng: 126.3498 },
    mapUrl: "https://www.google.com/maps/search/Kinilaw+King+Bislig",
    rating: 4.6
  },
  {
    id: "jollibee-mangagoy",
    name: "Jollibee Mangagoy",
    description: "The absolute favorite Filipino fast-food chain in Bislig City, serving legendary Chickenjoy, Jolly Spaghetti, and burgers to families and travelers.",
    longDescription: "A central gathering point for families in Bislig, Jollibee Mangagoy offers popular quick-service meals with distinct Filipino tastes. Conveniently located on the main coastal highway, it features a drive-thru, kids play area, and is the perfect stop to enjoy iconic Chickenjoy, sweet Jolly Spaghetti, and Peach Mango Pies during your road trip.",
    category: "Dining & Cafes",
    image: "/assets/images/jollibee.png",
    location: "Surigao-Davao Coastal Road, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 9999",
    socialMedia: "facebook.com/jollibeephilippines",
    website: "https://www.jollibee.com.ph",
    operatingHours: "07:00 AM - 10:00 PM daily",
    coordinates: { lat: 8.2072, lng: 126.3468 },
    mapUrl: "https://www.google.com/maps/search/Jollibee+Mangagoy+Bislig",
    rating: 4.5
  },
  {
    id: "kirbys-restaurant",
    name: "Kirby's Restaurant",
    description: "A long-standing local restaurant serving delicious, home-cooked Filipino dishes, Chinese-Filipino fusion, and family-sized platters.",
    longDescription: "Kirby's Restaurant is a classic Bislig dining venue popular for family reunions, birthdays, and business lunches. Its extensive menu features local favorites such as Crispy Pata, Pancit Canton, Beef Caldereta, and fresh seafood chop suey. With its comfortable air-conditioned seating and warm service, it provides a premium local dining environment.",
    category: "Dining & Cafes",
    image: "/assets/images/kirbys.jpg",
    location: "Espiritu St, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 4455",
    socialMedia: "facebook.com/kirbysrestaurantbislig",
    website: "",
    operatingHours: "09:00 AM - 09:00 PM daily",
    coordinates: { lat: 8.2079, lng: 126.3501 },
    mapUrl: "https://www.google.com/maps/search/Kirby%27s+Restaurant+Bislig",
    rating: 4.5
  },
  {
    id: "dmr-pharmacy",
    name: "DMR Pharmacy",
    description: "A localized pharmacy stocking prescription medications, over-the-counter drugs, and homeopathic/herbal health supplements.",
    longDescription: "DMR Pharmacy on Espiritu Street is a convenient neighborhood health shop offering standard prescription drugs, local generic medicines, skin care products, and wellness vitamins. Known for its quick service and accommodating pharmacists, it is a highly accessible healthcare spot in the commercial center.",
    category: "Services & Others",
    image: "/assets/images/dmr pharmacy.jpg",
    location: "Espiritu St, Brgy. Mangagoy, Bislig City",
    contact: "+63 930 222 1122",
    socialMedia: "facebook.com/dmrpharmacybislig",
    website: "",
    operatingHours: "08:00 AM - 08:00 PM daily",
    coordinates: { lat: 8.2090, lng: 126.3517 },
    mapUrl: "https://www.google.com/maps/search/DMR+Pharmacy+Mangagoy+Bislig",
    rating: 4.3
  },
  {
    id: "generika-bislig",
    name: "Generika Drugstore",
    description: "A well-known national generic drugstore chain offering affordable, high-quality generic medicines and health products in Poblacion.",
    longDescription: "Located in the historical Poblacion district of Bislig, Generika Drugstore provides affordable healthcare access. They specialize in high-quality generic equivalents of maintenance medicines and seasonal vitamins, backed by helpful patient consulting services. It is a highly trusted local pharmacy option.",
    category: "Services & Others",
    image: "/assets/images/generika drugstore.jpg",
    location: "National Highway, Brgy. Poblacion, Bislig City",
    contact: "+63 86 853 7788",
    socialMedia: "facebook.com/generikadrugstoreofficial",
    website: "https://www.generika.com.ph",
    operatingHours: "08:00 AM - 08:00 PM daily",
    coordinates: { lat: 8.2185, lng: 126.3601 },
    mapUrl: "https://www.google.com/maps/search/Generika+Drugstore+Poblacion+Bislig",
    rating: 4.5
  },
  {
    id: "city-vet-office",
    name: "City Veterinary Services Office",
    description: "The local government office providing public veterinary services, pet registration, rabies vaccinations, and livestock care.",
    longDescription: "The City Veterinary Services Office is located inside the City Hall Compound and handles agricultural and domestic animal health programs. Tourists and locals can visit for rabies vaccinations, pet medical consults, or to coordinate animal health certifications. They are highly active in maintaining public health standards across the municipality.",
    category: "Services & Others",
    image: "/assets/images/veterinary bislig.png",
    location: "City Hall Compound, Brgy. Poblacion, Bislig City",
    contact: "+63 86 853 6000",
    socialMedia: "facebook.com/cityvetbislig",
    website: "https://bislig.gov.ph/services/city-veterinary",
    operatingHours: "08:00 AM - 05:00 PM (Monday to Friday)",
    coordinates: { lat: 8.2180, lng: 126.3608 },
    mapUrl: "https://www.google.com/maps/search/City+Veterinary+Services+Office+Bislig",
    rating: 4.2
  },
  {
    id: "citi-side-inn",
    name: "Citi Side Inn",
    description: "Affordable, clean, and comfortable lodging located in the heart of Bislig, perfect for budget-conscious travelers.",
    longDescription: "Citi Side Inn is a premier budget-friendly accommodation option in Bislig City. Offering clean rooms equipped with air conditioning, cable television, and private bathrooms. Strategically located near commercial centers and transportation hubs, it provides guests with easy access to local markets, dining spots, and the public transport terminal to the waterfalls.",
    category: "Accommodations",
    image: "/assets/images/citi side inn.jpg",
    location: "Abarca Street, Brgy. Mangagoy, Bislig City",
    contact: "+63 918 222 3344",
    socialMedia: "facebook.com/citisideinn",
    website: "",
    operatingHours: "24/7 Front Desk",
    coordinates: { lat: 8.2095, lng: 126.3501 },
    mapUrl: "https://www.google.com/maps/search/Citi+Side+Inn+Bislig",
    rating: 4.3
  },
  {
    id: "prince-town-bislig",
    name: "Prince Town Bislig",
    description: "A major commercial store in Bislig, providing a wide variety of clothing, home goods, groceries, and retail choices.",
    longDescription: "Prince Town Bislig is a well-known retail landmark in Surigao del Sur. It is a highly popular one-stop department store and supermarket offering budget-friendly clothing, household essentials, appliances, toys, and school supplies. With its central location, it serves thousands of local residents and visitors daily.",
    category: "Shops & Malls",
    image: "/assets/images/Prince Town.jpg",
    location: "Abarca St, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 4488",
    socialMedia: "facebook.com/princetownbislig",
    website: "",
    operatingHours: "08:30 AM - 08:00 PM daily",
    coordinates: { lat: 8.2100, lng: 126.3510 },
    mapUrl: "https://www.google.com/maps/search/Prince+Town+Bislig",
    rating: 4.2
  },
  {
    id: "jf-department-store",
    name: "J&F Mall & Department Store",
    description: "A modern department store and shopping center in Bislig, featuring fashion, home items, and convenient groceries.",
    longDescription: "J&F Department Store offers a modern retail environment in Brgy. Mangagoy. It showcases a rich selection of trendy fashion apparel, shoes, home decor, electronics, and a supermarket on the lower level. It is a favorite shopping hub for local shoppers looking for quality merchandise and promotional deals.",
    category: "Shops & Malls",
    image: "/assets/images/J&F.jpg",
    location: "Espiritu Street, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 7799",
    socialMedia: "facebook.com/jfmallbislig",
    website: "",
    operatingHours: "09:00 AM - 08:30 PM daily",
    coordinates: { lat: 8.2093, lng: 126.3518 },
    mapUrl: "https://www.google.com/maps/search/JF+Department+Store+Bislig",
    rating: 4.3
  },
  {
    id: "ramz-square",
    name: "Ramz Square Food Hub & Entertainment",
    description: "A lively commercial plaza featuring local food hubs, open-air dining, and occasional acoustic nights in Mangagoy.",
    longDescription: "Ramz Square is a vibrant social hub at night in Bislig City. Featuring a lively open-air cluster of local food stalls, barbecue spots, beer gardens, and cafes. It is a highly popular weekend destination for group hangouts, offering live acoustic music performances and a relaxed chill vibe under fairy lights.",
    category: "Dining & Cafes",
    image: "/assets/images/ramz square.webp",
    location: "Surigao-Davao Coastal Highway, Brgy. Mangagoy, Bislig City",
    contact: "+63 949 111 5566",
    socialMedia: "facebook.com/ramzsquare",
    website: "",
    operatingHours: "03:00 PM - 12:00 AM daily",
    coordinates: { lat: 8.2070, lng: 126.3475 },
    mapUrl: "https://www.google.com/maps/search/Ramz+Square+Bislig",
    rating: 4.5
  },
  {
    id: "saint-vincent-parish",
    name: "Saint Vincent de Paul Parish Church",
    description: "A historic, beautiful parish church in Bislig serving as a spiritual sanctuary and cultural landmark.",
    longDescription: "The Saint Vincent de Paul Parish Church is one of the most prominent religious landmarks in Bislig City. Adorned with beautiful yellow facades and high arched ceilings, it holds regular masses and community gatherings. Built in dedication to Saint Vincent de Paul, it stands as a testament to the deep faith and cultural heritage of the local community.",
    category: "Churches & Landmarks",
    image: "/assets/images/Saint Vincent Parish.webp",
    location: "Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 1122",
    socialMedia: "facebook.com/saintvincentparishbislig",
    website: "",
    operatingHours: "06:00 AM - 07:00 PM daily",
    coordinates: { lat: 8.2075, lng: 126.3525 },
    mapUrl: "https://www.google.com/maps/search/Saint+Vincent+de+Paul+Parish+Bislig",
    rating: 4.7
  },
  {
    id: "ace-pickle-yard",
    name: "Ace Pickle Yard (Indoor Pickleball)",
    description: "A brand-new premium indoor pickleball facility offering excellent tournament courts and equipment rentals.",
    longDescription: "Ace Pickle Yard is the newest dedicated sports venue in Bislig City, catering to the booming popularity of pickleball. It features multiple indoor courts surfaced to professional specifications, providing shelter from sun and tropical rain. Popular for friendly games and local competitions, they offer paddle rentals, beginner training sessions, and cold sports refreshments.",
    category: "Sports & Recreation",
    image: "/assets/images/Ace Pickle Yard.jpg",
    location: "Espiritu Extension, Brgy. Mangagoy, Bislig City",
    contact: "+63 960 777 8899",
    socialMedia: "facebook.com/acepickleyard",
    website: "",
    operatingHours: "06:00 AM - 10:00 PM daily",
    coordinates: { lat: 8.2105, lng: 126.3530 },
    mapUrl: "https://www.google.com/maps/search/Ace+Pickle+Yard+Bislig",
    rating: 4.8
  },
  {
    id: "ocean-view-park-directory",
    name: "Ocean View Park Restaurant & Hill",
    description: "A scenic hilltop park with restaurant offering stunning bird's-eye views of Bislig Bay and paper mill towers.",
    longDescription: "Ocean View Park is a celebrated recreational attraction and viewpoint in Bislig. Situated atop a lush hill, visitors climb 100+ steps to be rewarded with panoramic vistas of the Bislig bayfront and the city landscape. Its on-site restaurant serves mouthwatering local Kamayo seafood and native drinks, making it a spectacular sunset dining destination.",
    category: "Attractions",
    image: "/assets/images/Ocean View Park.jpg",
    location: "Brgy. Cumawas, Bislig City",
    contact: "+63 86 853 4400",
    socialMedia: "facebook.com/oceanviewparkbislig",
    website: "",
    operatingHours: "05:00 AM - 09:00 PM daily",
    coordinates: { lat: 8.2120, lng: 126.3600 },
    mapUrl: "https://www.google.com/maps/search/Ocean+View+Park+Bislig",
    rating: 4.7
  },
  {
    id: "paper-country-inn-directory",
    name: "Paper Country Inn",
    description: "A historic, well-known hotel in the heart of Bislig offering comfy rooms, conference venues, and a cozy restaurant.",
    longDescription: "Paper Country Inn is one of the most established hotel properties in Bislig City. Celebrated for its warm service and comfortable guestrooms, it is a favorite lodging option for business travelers, government seminars, and tourists. It has an on-site cafe and restaurant serving native Filipino favorites, plus stable Wi-Fi and safe parking spaces.",
    category: "Accommodations",
    image: "/assets/images/paper country inn.webp",
    location: "Abarca St, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 3034",
    socialMedia: "facebook.com/papercountryinn",
    website: "",
    operatingHours: "24/7 Front Desk",
    coordinates: { lat: 8.2091, lng: 126.3499 },
    mapUrl: "https://www.google.com/maps/search/Paper+Country+Inn+Bislig",
    rating: 4.4
  },
  {
    id: "highland-hotel-directory",
    name: "Highland Hotel",
    description: "Modern hotel offering elevated city views, fully air-conditioned rooms, and prompt hospitality in Mangagoy.",
    longDescription: "Highland Hotel provides travelers with a clean, comfortable, and modern stay. Equipped with key amenities like cable television, free Wi-Fi, air conditioning, and a hot/cold shower. The friendly staff assists with travel bookings, including van hires to Tinuy-an Falls and Hinatuan.",
    category: "Accommodations",
    image: "/assets/images/highland hotel.webp",
    location: "Abarca St, Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 5500",
    socialMedia: "facebook.com/highlandhotelbislig",
    website: "",
    operatingHours: "24/7 Front Desk",
    coordinates: { lat: 8.2098, lng: 126.3505 },
    mapUrl: "https://www.google.com/maps/search/Highland+Hotel+Bislig",
    rating: 4.3
  },
  {
    id: "glc-suites-directory",
    name: "GLC Suites",
    description: "Clean, modern apartment-style suite rentals perfect for longer stays and families in Mangagoy.",
    longDescription: "GLC Suites offers apartment-style rentals in the commercial zone. Highly suitable for families and tour groups who need larger rooms, kitchenette configurations, and private dining spaces. It lies walking distance from primary retail shops, restaurants, and pharmacy lines.",
    category: "Accommodations",
    image: "/assets/images/GLC suites.webp",
    location: "Espiritu St, Brgy. Mangagoy, Bislig City",
    contact: "+63 919 444 8888",
    socialMedia: "facebook.com/glcsuites",
    website: "",
    operatingHours: "24/7 Front Desk",
    coordinates: { lat: 8.2085, lng: 126.3515 },
    mapUrl: "https://www.google.com/maps/search/GLC+Suites+Bislig",
    rating: 4.4
  },
  {
    id: "iglesia-ni-cristo-directory",
    name: "Iglesia ni Cristo House of Worship",
    description: "The magnificent, high-steeple landmark chapel of the Iglesia ni Cristo in Bislig.",
    longDescription: "This house of worship serves as the primary congregational chapel for the members of the Iglesia ni Cristo in Bislig City. Exhibiting the characteristic tall steeples and grand architectural outlines, it is located prominently along the roadway, serving as a landmark in the district.",
    category: "Churches & Landmarks",
    image: "/assets/images/Iglesia ni Cristo.webp",
    location: "National Highway, Brgy. Caramcam, Bislig City",
    contact: "N/A",
    socialMedia: "",
    website: "",
    operatingHours: "Mass/Service Times Only",
    coordinates: { lat: 8.2140, lng: 126.3550 },
    mapUrl: "https://www.google.com/maps/search/Iglesia+ni+Cristo+Bislig",
    rating: 4.6
  },
  {
    id: "i-love-bislig",
    name: "I Love Bislig Sign & Baywalk",
    description: "The iconic colorful landmark sign along the scenic Bislig Baywalk, perfect for souvenir photos and evening walks.",
    longDescription: "The 'I Love Bislig' sign is a vibrant and popular local landmark located along the picturesque Bislig City Baywalk. Featuring large, colorful illuminated letters, it serves as the ultimate welcoming emblem for visitors. The surrounding baywalk offers cool ocean breezes, sunset vistas over the bay, and stalls selling street food and native snacks, making it a favorite social hub for both locals and tourists alike.",
    category: "Attractions",
    image: "/assets/images/i love bislig.webp",
    location: "Bislig City Baywalk, Poblacion, Bislig City",
    contact: "Tourism Office: +63 86 853 6000",
    socialMedia: "facebook.com/bisligcitytourism",
    website: "",
    operatingHours: "Open 24/7 (best visited at sunset/evening for lighting)",
    coordinates: { lat: 8.2135, lng: 126.3570 },
    mapUrl: "https://www.google.com/maps/search/I+Love+Bislig+Sign+Baywalk",
    rating: 4.8
  },
  {
    id: "g88-water",
    name: "G88 Water Refilling Station",
    description: "A reliable local water refilling station providing purified and alkaline drinking water with home delivery options.",
    longDescription: "G88 Water Refilling Station is a trusted provider of clean, purified, and alkaline drinking water in Mangagoy, Bislig City. Utilizing state-of-the-art multi-stage filtration and sterilization systems, they ensure top-grade hydration for local households and businesses. They offer prompt delivery services and refills for standard containers.",
    category: "Services & Others",
    image: "/assets/images/G88 Water Refilling Station.jpg",
    location: "Picasales St., Brgy. Mangagoy, Bislig City",
    contact: "+63 915 888 8888",
    socialMedia: "facebook.com/profile.php?id=61584580967182",
    website: "",
    operatingHours: "08:00 AM - 05:00 PM daily",
    coordinates: { lat: 8.2095, lng: 126.3512 },
    mapUrl: "https://www.google.com/maps/search/G88+Water+Refilling+Station+Bislig",
    rating: 4.7
  },
  {
    id: "golden-88-trading",
    name: "Golden 88 Primate Trading Corp",
    description: "A prominent local wholesale and retail grocery store stocking fresh food, household essentials, and pantry goods.",
    longDescription: "Golden 88 Primate Trading Corp is one of Mangagoy's leading wholesale and retail grocery outlets. It provides an extensive selection of local and imported goods, fresh produce, frozen meat, kitchen supplies, and everyday pantry essentials at highly competitive prices, serving as a primary supply hub for residents and small convenience stores.",
    category: "Shops & Malls",
    image: "/assets/images/Golden 88 Trading.webp",
    location: "Picasales St., Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 1188",
    socialMedia: "facebook.com/golden88trading",
    website: "",
    operatingHours: "07:30 AM - 06:30 PM daily",
    coordinates: { lat: 8.2078, lng: 126.3524 },
    mapUrl: "https://www.google.com/maps/search/Golden+88+Trading+Mangagoy+Bislig",
    rating: 4.6
  },
  {
    id: "ericson-minimart",
    name: "Ericson Minimart",
    description: "A friendly, fully-stocked neighborhood minimart providing quick convenience items, snacks, and daily household needs.",
    longDescription: "Ericson Minimart offers a quick and easy shopping experience for local residents in Mangagoy. Stocked with essential toiletries, canned goods, ice cream, soft drinks, instant snacks, and basic household items, it is a convenient stop for quick runs without the crowds of large department stores.",
    category: "Shops & Malls",
    image: "/assets/images/ericson minimart.jpg",
    location: "Picasales St., Brgy. Mangagoy, Bislig City",
    contact: "+63 909 555 1234",
    socialMedia: "facebook.com/ericsonminimart",
    website: "",
    operatingHours: "06:00 AM - 09:00 PM daily",
    coordinates: { lat: 8.2089, lng: 126.3540 },
    mapUrl: "https://www.google.com/maps/search/Ericson+Minimart+Mangagoy+Bislig",
    rating: 4.5
  },
  {
    id: "narsala-store",
    name: "Narsala Store",
    description: "A popular general merchandise stall located within the Rehab Public Market, offering budget-friendly clothing, accessories, and home goods.",
    longDescription: "Narsala Store is a well-known retail stall located inside the busy Rehab Public Market on Picasales St., Mangagoy. It caters to locals looking for affordable clothing, textiles, home accessories, footwear, and general merchandise in a lively marketplace setting.",
    category: "Shops & Malls",
    image: "/assets/images/Narsala store.jpg",
    location: "Rehab Public Market, Picasales St., Brgy. Mangagoy, Bislig City",
    contact: "+63 948 333 4444",
    socialMedia: "",
    website: "",
    operatingHours: "05:00 AM - 06:00 PM daily",
    coordinates: { lat: 8.2065, lng: 126.3510 },
    mapUrl: "https://www.google.com/maps/search/Rehab+Public+Market+Mangagoy+Bislig",
    rating: 4.4
  },
  {
    id: "leteres-store",
    name: "Leteres Store",
    description: "A long-running dry goods and general store located right next to Sheila's Bakeshop on Picasales Street.",
    longDescription: "Leteres Store is a convenient neighborhood general store situated directly beside the popular Sheila's Bakeshop along Picasales Street. Serving the community with daily dry goods, school supplies, cooking ingredients, snacks, and household sundries, it is a staple fixture of the local neighborhood shopping strip.",
    category: "Shops & Malls",
    image: "/assets/images/Leteres Store Mangagoy.jpg",
    location: "Picasales St. (beside Sheila's Bakeshop), Brgy. Mangagoy, Bislig City",
    contact: "+63 930 777 9999",
    socialMedia: "",
    website: "",
    operatingHours: "06:00 AM - 08:30 PM daily",
    coordinates: { lat: 8.2072, lng: 126.3528 },
    mapUrl: "https://www.google.com/maps/search/Leteres+Store+Mangagoy+Bislig",
    rating: 4.5
  },
  {
    id: "botica-leosala",
    name: "Botica Leosala",
    description: "A trusted community pharmacy providing essential prescription medications, over-the-counter drugs, and health vitamins.",
    longDescription: "Botica Leosala is a dedicated community pharmacy and drug store located on Picasales St., Mangagoy. Known for its friendly pharmacists and accessible price points, it stocks high-quality generic and branded medicines, medical supplies, health supplements, and baby care products to meet local family needs.",
    category: "Services & Others",
    image: "/assets/images/Botica Leosala.webp",
    location: "Picasales St., Brgy. Mangagoy, Bislig City",
    contact: "+63 86 853 5544",
    socialMedia: "",
    website: "",
    operatingHours: "07:00 AM - 08:00 PM daily",
    coordinates: { lat: 8.2070, lng: 126.3532 },
    mapUrl: "https://www.google.com/maps/search/Botica+Leosala+Mangagoy+Bislig",
    rating: 4.6
  }
];
